version: '3.7'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    image: simde_portal_app:latest # Required to get the generated public folder
    working_dir: /var/www/html
    depends_on:
      - database
    env_file:
      - docker/.env.docker

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=portail
      - MYSQL_DATABASE=portail

volumes:
  dbdata:
